#!/usr/bin/env bash

set -e

if [[ $EUID -ne 0 ]]; then
	echo Run as root!
	exit 1
fi

function command_exists() {
	builtin type -P "$1" &>/dev/null || eval "$1" &>/dev/null
}

# docker compose v2 is not a python package (`docker-compose`),
# but a reimplementation in Go (`docker compose`).
# Either of them works for us.
POSSIBLE_DOCKER_COMPOSE=("docker compose" "docker-compose")
for cmd in "${POSSIBLE_DOCKER_COMPOSE[@]}"; do
	if command_exists "$cmd"; then
		echo "'$cmd' exists, using that."
		read -r -a DC_CMD <<<"$cmd"
		break
	fi
done

if [[ ${#DC_CMD[@]} -eq 0 ]]; then
	echo Docker compose doesn\'t seem to be installed.
	exit 1
fi

if [ -z "$COMPOSEFLAGS" ]; then
	COMPOSE_FLAGS=("-d" "--remove-orphans")
fi

function stop() {
	"${DC_CMD[@]}" --profile cloudflared --profile letsencrypt down
}

function run() {
	if [ ! -e ./.env ]; then
		read -r -p 'Domain that will serve the mirror: ' domain
		echo "DOMAIN_NAME=$domain" >./.env
		read -p "Automatically manage web server (letsencrypt, cloudflare tunnels) y/N " -n 1 -r
		echo
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			read -p "Use cloudflare tunnels y/N " -n 1 -r
			echo
			if [[ $REPLY =~ ^[Yy]$ ]]; then
				echo "USE_TUNNELS=true" >>./.env
				echo "SSL_FILE=/dev/null" >>./.env
			else
				read -r -p 'Your email address: ' email
				echo "EMAIL=$email" >>./.env
			fi
		else
			read -p "Webroot path (optional): " -r webroot
			if [ -n "$webroot" ]; then
				echo "WEBROOT=$webroot" >>./.env
			fi
			echo "NO_WEB=true" >>./.env
		fi
	fi

	source .env

	if [ "$USE_TUNNELS" == "true" ]; then
		if [ ! -e "./data/cloudflared/home/.cloudflared/cert.pem" ]; then
			"${DC_CMD[@]}" -f docker-compose.yml run --rm cloudflared login
			"${DC_CMD[@]}" -f docker-compose.yml run --rm cloudflared --origincert /root/.cloudflared/cert.pem tunnel create "$DOMAIN_NAME"
			"${DC_CMD[@]}" -f docker-compose.yml run --rm cloudflared --origincert /root/.cloudflared/cert.pem tunnel route dns "$DOMAIN_NAME" "$DOMAIN_NAME"
		fi
	elif [ "$NO_WEB" != "true" ]; then
		if [ ! -e ./data/letsencrypt/etc/renewal/chaotic.conf ]; then
			# shellcheck disable=SC2153
			docker run -p 80:80 -p 443:443 --rm -v "$PWD/data/letsencrypt/etc:/etc/letsencrypt" -v "$PWD/data/letsencrypt/var:/var/lib/letsencrypt" certbot/certbot:"${LETSENCRYPT_TAG:-latest}" certonly --standalone --non-interactive --agree-tos --cert-name chaotic -n -m "$EMAIL" -d "$DOMAIN_NAME"
		fi
	fi

	if [ ! -e ./http-root/chaotic-aur ] && [ "$NO_WEB" != "true" ]; then
		# Convert legacy
		if [ -d ./repo ]; then
			stop
			mkdir ./http-root
			mv ./repo ./http-root/chaotic-aur
		else
			mkdir -p ./http-root/chaotic-aur/.stfolder
			chown -R 1000:1000 ./http-root/chaotic-aur/
		fi
	fi

	if [ ! -e ./data/syncthing/config.xml ]; then
		mkdir -p ./data/syncthing
		cp ./preset/syncthing-config.xml ./data/syncthing/config.xml
		chown -R 1000:1000 ./data/syncthing
	fi

	gawk -i inplace '/<folder id="jhcrt-m2dra"/ {
    begin = 1
  }
  /<minDiskFree unit="">0<\/minDiskFree>/ {
    if (begin) {
      print "        <minDiskFree unit=\"%\">1</minDiskFree>"
      next
    } else {
      print
    }
  }
  /<\/folder>/ {
    begin = 0
  }
  1' ./data/syncthing/config.xml

	if [ -n "$UPDATE_IMAGES" ]; then
		COMPOSE_FLAGS+=("--pull" "always")
	fi

	if [ "$NO_WEB" == "true" ]; then
		"${DC_CMD[@]}" up "${COMPOSE_FLAGS[@]}"
	elif [ "$USE_TUNNELS" == "true" ]; then
		"${DC_CMD[@]}" --profile cloudflared up "${COMPOSE_FLAGS[@]}"
	else
		"${DC_CMD[@]}" --profile letsencrypt up "${COMPOSE_FLAGS[@]}"
	fi
}

function update() {
	stop

	if [ ! -d "./.git" ]; then
		if [ "$(git rev-parse --is-inside-work-tree || true)" == "true" ]; then
			echo "Please run this script in the main directory"
			exit 1
		fi
		git init --initial-branch=main
		git remote add origin https://github.com/chaotic-aur/docker-mirror
		git fetch
		git reset --hard origin/main
	elif [ ! -f ./custom.diff ]; then
		git pull || {
			echo "Git pull failed, please fix the issue at hand."
			exit 1
		}
	else
		git fetch
		git reset --hard origin/main
		git apply ./custom.diff
	fi

	if [ "$SELFUPDATE" != 1 ]; then
		SELFUPDATE=1 update
	fi

	UPDATE_IMAGES=true run
}

case "${1:-}" in
"update")
	update
	;;
"stop")
	stop
	;;
"run")
	run
	;;
*)
	echo "Usage: $0 {update|stop|run}"
	echo "  update: Stop, update with latest images, and start the containers"
	echo "  stop: Stop all the containers"
	echo "  run: Start all the containers"
	exit 1
	;;
esac
