#!/bin/bash

set -e

if [[ $EUID -ne 0 ]]; then
    echo Run as root!
    exit 1
fi

if [ -e "./data/cloudflared/home/.cloudflared/cert.pem" ]; then
    docker compose -f docker-compose-tunnels.yml down
    docker compose -f docker-compose.yml down
else
    docker compose -f docker-compose.yml down
    docker compose -f docker-compose-tunnels.yml down
fi
